---

- name: Install the required  packages in Redhat derivatives
  yum: name={{ item }} state=latest
  with_items: '{{ ntp_pkgs }}'

- name: Configure ntp.conf
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify: 
   - Restart chronyd
