---

- name: Install chrony
  yum: name={{ item }} state=latest
  with_items: '{{ chrony_pkgs }}'

- name: Configure ntp.conf
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify: 
   - Restart chronyd
